// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shinplay/ent/otp"
	"github.com/shinplay/ent/predicate"
	"github.com/shinplay/ent/user"
)

// OTPUpdate is the builder for updating OTP entities.
type OTPUpdate struct {
	config
	hooks    []Hook
	mutation *OTPMutation
}

// Where appends a list predicates to the OTPUpdate builder.
func (ou *OTPUpdate) Where(ps ...predicate.OTP) *OTPUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetUpdateTime sets the "update_time" field.
func (ou *OTPUpdate) SetUpdateTime(t time.Time) *OTPUpdate {
	ou.mutation.SetUpdateTime(t)
	return ou
}

// SetOtp sets the "otp" field.
func (ou *OTPUpdate) SetOtp(s string) *OTPUpdate {
	ou.mutation.SetOtp(s)
	return ou
}

// SetNillableOtp sets the "otp" field if the given value is not nil.
func (ou *OTPUpdate) SetNillableOtp(s *string) *OTPUpdate {
	if s != nil {
		ou.SetOtp(*s)
	}
	return ou
}

// SetExpiresAt sets the "expires_at" field.
func (ou *OTPUpdate) SetExpiresAt(t time.Time) *OTPUpdate {
	ou.mutation.SetExpiresAt(t)
	return ou
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (ou *OTPUpdate) SetNillableExpiresAt(t *time.Time) *OTPUpdate {
	if t != nil {
		ou.SetExpiresAt(*t)
	}
	return ou
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ou *OTPUpdate) SetUserID(id int) *OTPUpdate {
	ou.mutation.SetUserID(id)
	return ou
}

// SetUser sets the "user" edge to the User entity.
func (ou *OTPUpdate) SetUser(u *User) *OTPUpdate {
	return ou.SetUserID(u.ID)
}

// Mutation returns the OTPMutation object of the builder.
func (ou *OTPUpdate) Mutation() *OTPMutation {
	return ou.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ou *OTPUpdate) ClearUser() *OTPUpdate {
	ou.mutation.ClearUser()
	return ou
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OTPUpdate) Save(ctx context.Context) (int, error) {
	ou.defaults()
	return withHooks(ctx, ou.sqlSave, ou.mutation, ou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OTPUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OTPUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OTPUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ou *OTPUpdate) defaults() {
	if _, ok := ou.mutation.UpdateTime(); !ok {
		v := otp.UpdateDefaultUpdateTime()
		ou.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ou *OTPUpdate) check() error {
	if v, ok := ou.mutation.Otp(); ok {
		if err := otp.OtpValidator(v); err != nil {
			return &ValidationError{Name: "otp", err: fmt.Errorf(`ent: validator failed for field "OTP.otp": %w`, err)}
		}
	}
	if ou.mutation.UserCleared() && len(ou.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OTP.user"`)
	}
	return nil
}

func (ou *OTPUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ou.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(otp.Table, otp.Columns, sqlgraph.NewFieldSpec(otp.FieldID, field.TypeInt))
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.UpdateTime(); ok {
		_spec.SetField(otp.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := ou.mutation.Otp(); ok {
		_spec.SetField(otp.FieldOtp, field.TypeString, value)
	}
	if value, ok := ou.mutation.ExpiresAt(); ok {
		_spec.SetField(otp.FieldExpiresAt, field.TypeTime, value)
	}
	if ou.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   otp.UserTable,
			Columns: []string{otp.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   otp.UserTable,
			Columns: []string{otp.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{otp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ou.mutation.done = true
	return n, nil
}

// OTPUpdateOne is the builder for updating a single OTP entity.
type OTPUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OTPMutation
}

// SetUpdateTime sets the "update_time" field.
func (ouo *OTPUpdateOne) SetUpdateTime(t time.Time) *OTPUpdateOne {
	ouo.mutation.SetUpdateTime(t)
	return ouo
}

// SetOtp sets the "otp" field.
func (ouo *OTPUpdateOne) SetOtp(s string) *OTPUpdateOne {
	ouo.mutation.SetOtp(s)
	return ouo
}

// SetNillableOtp sets the "otp" field if the given value is not nil.
func (ouo *OTPUpdateOne) SetNillableOtp(s *string) *OTPUpdateOne {
	if s != nil {
		ouo.SetOtp(*s)
	}
	return ouo
}

// SetExpiresAt sets the "expires_at" field.
func (ouo *OTPUpdateOne) SetExpiresAt(t time.Time) *OTPUpdateOne {
	ouo.mutation.SetExpiresAt(t)
	return ouo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (ouo *OTPUpdateOne) SetNillableExpiresAt(t *time.Time) *OTPUpdateOne {
	if t != nil {
		ouo.SetExpiresAt(*t)
	}
	return ouo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ouo *OTPUpdateOne) SetUserID(id int) *OTPUpdateOne {
	ouo.mutation.SetUserID(id)
	return ouo
}

// SetUser sets the "user" edge to the User entity.
func (ouo *OTPUpdateOne) SetUser(u *User) *OTPUpdateOne {
	return ouo.SetUserID(u.ID)
}

// Mutation returns the OTPMutation object of the builder.
func (ouo *OTPUpdateOne) Mutation() *OTPMutation {
	return ouo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ouo *OTPUpdateOne) ClearUser() *OTPUpdateOne {
	ouo.mutation.ClearUser()
	return ouo
}

// Where appends a list predicates to the OTPUpdate builder.
func (ouo *OTPUpdateOne) Where(ps ...predicate.OTP) *OTPUpdateOne {
	ouo.mutation.Where(ps...)
	return ouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OTPUpdateOne) Select(field string, fields ...string) *OTPUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated OTP entity.
func (ouo *OTPUpdateOne) Save(ctx context.Context) (*OTP, error) {
	ouo.defaults()
	return withHooks(ctx, ouo.sqlSave, ouo.mutation, ouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OTPUpdateOne) SaveX(ctx context.Context) *OTP {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OTPUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OTPUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ouo *OTPUpdateOne) defaults() {
	if _, ok := ouo.mutation.UpdateTime(); !ok {
		v := otp.UpdateDefaultUpdateTime()
		ouo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ouo *OTPUpdateOne) check() error {
	if v, ok := ouo.mutation.Otp(); ok {
		if err := otp.OtpValidator(v); err != nil {
			return &ValidationError{Name: "otp", err: fmt.Errorf(`ent: validator failed for field "OTP.otp": %w`, err)}
		}
	}
	if ouo.mutation.UserCleared() && len(ouo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OTP.user"`)
	}
	return nil
}

func (ouo *OTPUpdateOne) sqlSave(ctx context.Context) (_node *OTP, err error) {
	if err := ouo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(otp.Table, otp.Columns, sqlgraph.NewFieldSpec(otp.FieldID, field.TypeInt))
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OTP.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, otp.FieldID)
		for _, f := range fields {
			if !otp.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != otp.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.UpdateTime(); ok {
		_spec.SetField(otp.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := ouo.mutation.Otp(); ok {
		_spec.SetField(otp.FieldOtp, field.TypeString, value)
	}
	if value, ok := ouo.mutation.ExpiresAt(); ok {
		_spec.SetField(otp.FieldExpiresAt, field.TypeTime, value)
	}
	if ouo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   otp.UserTable,
			Columns: []string{otp.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   otp.UserTable,
			Columns: []string{otp.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OTP{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{otp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouo.mutation.done = true
	return _node, nil
}
