// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shinplay/ent/otp"
	"github.com/shinplay/ent/user"
)

// OTPCreate is the builder for creating a OTP entity.
type OTPCreate struct {
	config
	mutation *OTPMutation
	hooks    []Hook
}

// SetOtp sets the "otp" field.
func (oc *OTPCreate) SetOtp(s string) *OTPCreate {
	oc.mutation.SetOtp(s)
	return oc
}

// SetNillableOtp sets the "otp" field if the given value is not nil.
func (oc *OTPCreate) SetNillableOtp(s *string) *OTPCreate {
	if s != nil {
		oc.SetOtp(*s)
	}
	return oc
}

// SetExpiresAt sets the "expires_at" field.
func (oc *OTPCreate) SetExpiresAt(t time.Time) *OTPCreate {
	oc.mutation.SetExpiresAt(t)
	return oc
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (oc *OTPCreate) SetNillableExpiresAt(t *time.Time) *OTPCreate {
	if t != nil {
		oc.SetExpiresAt(*t)
	}
	return oc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (oc *OTPCreate) SetUserID(id int) *OTPCreate {
	oc.mutation.SetUserID(id)
	return oc
}

// SetUser sets the "user" edge to the User entity.
func (oc *OTPCreate) SetUser(u *User) *OTPCreate {
	return oc.SetUserID(u.ID)
}

// Mutation returns the OTPMutation object of the builder.
func (oc *OTPCreate) Mutation() *OTPMutation {
	return oc.mutation
}

// Save creates the OTP in the database.
func (oc *OTPCreate) Save(ctx context.Context) (*OTP, error) {
	oc.defaults()
	return withHooks(ctx, oc.sqlSave, oc.mutation, oc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (oc *OTPCreate) SaveX(ctx context.Context) *OTP {
	v, err := oc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oc *OTPCreate) Exec(ctx context.Context) error {
	_, err := oc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oc *OTPCreate) ExecX(ctx context.Context) {
	if err := oc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (oc *OTPCreate) defaults() {
	if _, ok := oc.mutation.Otp(); !ok {
		v := otp.DefaultOtp()
		oc.mutation.SetOtp(v)
	}
	if _, ok := oc.mutation.ExpiresAt(); !ok {
		v := otp.DefaultExpiresAt
		oc.mutation.SetExpiresAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oc *OTPCreate) check() error {
	if _, ok := oc.mutation.Otp(); !ok {
		return &ValidationError{Name: "otp", err: errors.New(`ent: missing required field "OTP.otp"`)}
	}
	if v, ok := oc.mutation.Otp(); ok {
		if err := otp.OtpValidator(v); err != nil {
			return &ValidationError{Name: "otp", err: fmt.Errorf(`ent: validator failed for field "OTP.otp": %w`, err)}
		}
	}
	if _, ok := oc.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OTP.expires_at"`)}
	}
	if len(oc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "OTP.user"`)}
	}
	return nil
}

func (oc *OTPCreate) sqlSave(ctx context.Context) (*OTP, error) {
	if err := oc.check(); err != nil {
		return nil, err
	}
	_node, _spec := oc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	oc.mutation.id = &_node.ID
	oc.mutation.done = true
	return _node, nil
}

func (oc *OTPCreate) createSpec() (*OTP, *sqlgraph.CreateSpec) {
	var (
		_node = &OTP{config: oc.config}
		_spec = sqlgraph.NewCreateSpec(otp.Table, sqlgraph.NewFieldSpec(otp.FieldID, field.TypeInt))
	)
	if value, ok := oc.mutation.Otp(); ok {
		_spec.SetField(otp.FieldOtp, field.TypeString, value)
		_node.Otp = value
	}
	if value, ok := oc.mutation.ExpiresAt(); ok {
		_spec.SetField(otp.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if nodes := oc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   otp.UserTable,
			Columns: []string{otp.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OTPCreateBulk is the builder for creating many OTP entities in bulk.
type OTPCreateBulk struct {
	config
	err      error
	builders []*OTPCreate
}

// Save creates the OTP entities in the database.
func (ocb *OTPCreateBulk) Save(ctx context.Context) ([]*OTP, error) {
	if ocb.err != nil {
		return nil, ocb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ocb.builders))
	nodes := make([]*OTP, len(ocb.builders))
	mutators := make([]Mutator, len(ocb.builders))
	for i := range ocb.builders {
		func(i int, root context.Context) {
			builder := ocb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OTPMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ocb *OTPCreateBulk) SaveX(ctx context.Context) []*OTP {
	v, err := ocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ocb *OTPCreateBulk) Exec(ctx context.Context) error {
	_, err := ocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ocb *OTPCreateBulk) ExecX(ctx context.Context) {
	if err := ocb.Exec(ctx); err != nil {
		panic(err)
	}
}
